/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as GameCodeRouteImport } from "./routes/game.$code";
import { Route as GameCodeWatchRouteImport } from "./routes/game.$code_.watch";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const GameCodeRoute = GameCodeRouteImport.update({
  id: "/game/$code",
  path: "/game/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const GameCodeWatchRoute = GameCodeWatchRouteImport.update({
  id: "/game/$code_/watch",
  path: "/game/$code/watch",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/game/$code": typeof GameCodeRoute;
  "/game/$code/watch": typeof GameCodeWatchRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/game/$code": typeof GameCodeRoute;
  "/game/$code/watch": typeof GameCodeWatchRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/game/$code": typeof GameCodeRoute;
  "/game/$code_/watch": typeof GameCodeWatchRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$" | "/game/$code" | "/game/$code/watch";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$" | "/game/$code" | "/game/$code/watch";
  id: "__root__" | "/" | "/$" | "/game/$code" | "/game/$code_/watch";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  GameCodeRoute: typeof GameCodeRoute;
  GameCodeWatchRoute: typeof GameCodeWatchRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game/$code": {
      id: "/game/$code";
      path: "/game/$code";
      fullPath: "/game/$code";
      preLoaderRoute: typeof GameCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game/$code_/watch": {
      id: "/game/$code_/watch";
      path: "/game/$code/watch";
      fullPath: "/game/$code/watch";
      preLoaderRoute: typeof GameCodeWatchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GameCodeRoute: GameCodeRoute,
  GameCodeWatchRoute: GameCodeWatchRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
