/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/ui/theme/bagarre.source.ts
 * Command: astryx theme build src/ui/theme/bagarre.source.ts --out src/ui/theme/bagarre.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./bagarre.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const bagarreTheme: DefinedTheme;
